// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id may include a runtime prefix, e.g. "containerd://abc123..."
	// or be a bare 64-hex-char container ID.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// target_time is the absolute fake wall-clock time to set. The agent
	// converts this to an offset from time.Now() right before writing it into
	// the trampoline's state struct.
	TargetTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRequest) Reset() {
	*x = InjectRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRequest) ProtoMessage() {}

func (x *InjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRequest.ProtoReflect.Descriptor instead.
func (*InjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InjectRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *InjectRequest) GetTargetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetTime
	}
	return nil
}

type InjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectResponse) Reset() {
	*x = InjectResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectResponse) ProtoMessage() {}

func (x *InjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectResponse.ProtoReflect.Descriptor instead.
func (*InjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *InjectResponse) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type SetTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	TargetTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimeRequest) Reset() {
	*x = SetTimeRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeRequest) ProtoMessage() {}

func (x *SetTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeRequest.ProtoReflect.Descriptor instead.
func (*SetTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SetTimeRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

func (x *SetTimeRequest) GetTargetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetTime
	}
	return nil
}

type SetTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTimeResponse) Reset() {
	*x = SetTimeResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTimeResponse) ProtoMessage() {}

func (x *SetTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTimeResponse.ProtoReflect.Descriptor instead.
func (*SetTimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ResetRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HandleId       string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	LastTargetTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_target_time,json=lastTargetTime,proto3" json:"last_target_time,omitempty"` // last time passed to Inject or SetTime
	StateAddr      string                 `protobuf:"bytes,3,opt,name=state_addr,json=stateAddr,proto3" json:"state_addr,omitempty"`                  // hex, e.g. "0x7ffd1234abcd" — for debugging
	Generation     uint32                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`                                // bumped on each SetTime; 0 after Inject
	Pid            int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                                              // host PID of the injected process
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

func (x *StatusResponse) GetLastTargetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTargetTime
	}
	return nil
}

func (x *StatusResponse) GetStateAddr() string {
	if x != nil {
		return x.StateAddr
	}
	return ""
}

func (x *StatusResponse) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x0fepochd.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"o\n" +
	"\rInjectRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12;\n" +
	"\vtarget_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"targetTime\"-\n" +
	"\x0eInjectResponse\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\"j\n" +
	"\x0eSetTimeRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\x12;\n" +
	"\vtarget_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"targetTime\"\x11\n" +
	"\x0fSetTimeResponse\"+\n" +
	"\fResetRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\"\x0f\n" +
	"\rResetResponse\",\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\"\xc4\x01\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\x12D\n" +
	"\x10last_target_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastTargetTime\x12\x1d\n" +
	"\n" +
	"state_addr\x18\x03 \x01(\tR\tstateAddr\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\rR\n" +
	"generation\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid2\xba\x02\n" +
	"\fAgentService\x12I\n" +
	"\x06Inject\x12\x1e.epochd.agent.v1.InjectRequest\x1a\x1f.epochd.agent.v1.InjectResponse\x12L\n" +
	"\aSetTime\x12\x1f.epochd.agent.v1.SetTimeRequest\x1a .epochd.agent.v1.SetTimeResponse\x12F\n" +
	"\x05Reset\x12\x1d.epochd.agent.v1.ResetRequest\x1a\x1e.epochd.agent.v1.ResetResponse\x12I\n" +
	"\x06Status\x12\x1e.epochd.agent.v1.StatusRequest\x1a\x1f.epochd.agent.v1.StatusResponseB\x14Z\x12epochd/pkg/agentpbb\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(*InjectRequest)(nil),         // 0: epochd.agent.v1.InjectRequest
	(*InjectResponse)(nil),        // 1: epochd.agent.v1.InjectResponse
	(*SetTimeRequest)(nil),        // 2: epochd.agent.v1.SetTimeRequest
	(*SetTimeResponse)(nil),       // 3: epochd.agent.v1.SetTimeResponse
	(*ResetRequest)(nil),          // 4: epochd.agent.v1.ResetRequest
	(*ResetResponse)(nil),         // 5: epochd.agent.v1.ResetResponse
	(*StatusRequest)(nil),         // 6: epochd.agent.v1.StatusRequest
	(*StatusResponse)(nil),        // 7: epochd.agent.v1.StatusResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	8, // 0: epochd.agent.v1.InjectRequest.target_time:type_name -> google.protobuf.Timestamp
	8, // 1: epochd.agent.v1.SetTimeRequest.target_time:type_name -> google.protobuf.Timestamp
	8, // 2: epochd.agent.v1.StatusResponse.last_target_time:type_name -> google.protobuf.Timestamp
	0, // 3: epochd.agent.v1.AgentService.Inject:input_type -> epochd.agent.v1.InjectRequest
	2, // 4: epochd.agent.v1.AgentService.SetTime:input_type -> epochd.agent.v1.SetTimeRequest
	4, // 5: epochd.agent.v1.AgentService.Reset:input_type -> epochd.agent.v1.ResetRequest
	6, // 6: epochd.agent.v1.AgentService.Status:input_type -> epochd.agent.v1.StatusRequest
	1, // 7: epochd.agent.v1.AgentService.Inject:output_type -> epochd.agent.v1.InjectResponse
	3, // 8: epochd.agent.v1.AgentService.SetTime:output_type -> epochd.agent.v1.SetTimeResponse
	5, // 9: epochd.agent.v1.AgentService.Reset:output_type -> epochd.agent.v1.ResetResponse
	7, // 10: epochd.agent.v1.AgentService.Status:output_type -> epochd.agent.v1.StatusResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
